version: "3"
services:

  redis:
    image: library/redis:6.2.1
    ports:
      - 6379:6379

  mariadb:
    image: library/mariadb:10.3.28
    environment:
      MYSQL_DATABASE: dev_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  application:
    build: .
    expose:
      - 8080
    depends_on:
      - mariadb
      - redis