version: "3"
services:

  redis:
    image: library/redis:6.2.1
    ports:
      - 6378:6379

  mariadb:
    image: library/mariadb:10.3.28
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: mydb_dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    ports:
      - 3305:3306
